**Data Cleaning**

Import libraries

In [1]:
import pandas as pd
import numpy as np

In [9]:
pip install openpyxl

Collecting openpyxlNote: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

Load data

In [10]:
file_path = r"D:\Lulu_Mall_Retail_Analytics recent\Lulu_Mall_Sales_Dataset.xlsx"
df = pd.read_excel(file_path)
df.head()

,Order_ID,Order_Date,Store_ID,Store_Name,City,State,Region,Customer_ID,Customer_Gender,Product_Category,Product_Name,Quantity,Unit_Price,Revenue,Payment_Mode
0,ORD0100,2024-01-01,STR005,Lulu Mall Mumbai,Mumbai,Maharashtra,West,CUST0556,Female,Fashion,Adidas Women's Sports Shoes,1,5123,5123,UPI
1,ORD0763,2024-01-01,STR007,Lulu Mall Lucknow,Lucknow,Uttar Pradesh,North,CUST0073,Female,Beauty,Dove Body Lotion 400ml,1,571,571,UPI
2,ORD0654,2024-01-02,STR005,Lulu Mall Mumbai,Mumbai,Maharashtra,West,CUST0260,Male,Grocery,Haldiram's Bhujia Sev 1kg,3,439,1317,Net Banking
3,ORD0485,2024-01-03,STR003,Lulu Mall Chennai,Chennai,Tamil Nadu,South,CUST0727,Male,Electronics,Redmi Note 13 Pro,1,22889,22889,EMI
4,ORD0926,2024-01-03,STR003,Lulu Mall Chennai,Chennai,Tamil Nadu,South,CUST0242,Male,Fashion,Raymond Men's Formal Shirt,2,2373,4746,EMI

 Understand the data

In [11]:
df.shape

(1200, 15)

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          1200 non-null   str
 1   Order_Date        1200 non-null   datetime64[us]
 2   Store_ID          1200 non-null   str
 3   Store_Name        1200 non-null   str
 4   City              1200 non-null   str
 5   State             1200 non-null   str
 6   Region            1200 non-null   str
 7   Customer_ID       1200 non-null   str
 8   Customer_Gender   1200 non-null   str
 9   Product_Category  1200 non-null   str
 10  Product_Name      1200 non-null   str
 11  Quantity          1200 non-null   int64
 12  Unit_Price        1200 non-null   int64
 13  Revenue           1200 non-null   int64
 14  Payment_Mode      1200 non-null   str
dtypes: datetime64[us](1), int64(3), str(11)
memory usage: 266.0 KB

In [13]:
df.describe()

                Order_Date     Quantity    Unit_Price        Revenue
count                 1200  1200.000000   1200.000000    1200.000000
mean   2024-07-06 20:58:48     2.073333  10171.718333   21180.185000
min    2024-01-01 00:00:00     1.000000    151.000000     151.000000
25%    2024-04-04 00:00:00     1.000000    822.000000    1468.000000
50%    2024-07-09 00:00:00     2.000000   2531.500000    4415.500000
75%    2024-10-07 00:00:00     3.000000   8236.250000   15300.250000
max    2024-12-31 00:00:00     5.000000  83058.000000  402190.000000
std                    NaN     1.180727  17770.502834   44975.187023

In [14]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Store_ID            0
Store_Name          0
City                0
State               0
Region              0
Customer_ID         0
Customer_Gender     0
Product_Category    0
Product_Name        0
Quantity            0
Unit_Price          0
Revenue             0
Payment_Mode        0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

Validate the data

Check dates

In [19]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])
print(df["Order_Date"].min())
print(df["Order_Date"].max())

2024-01-01 00:00:00
2024-12-31 00:00:00

Check quantities

In [20]:
df[df["Quantity"] <= 0]

Empty DataFrame
Columns: [Order_ID, Order_Date, Store_ID, Store_Name, City, State, Region, Customer_ID, Customer_Gender, Product_Category, Product_Name, Quantity, Unit_Price, Revenue, Payment_Mode]
Index: []

Validate revenue

In [21]:
df["Calculated_Revenue"] = (
    df["Quantity"] * df["Unit_Price"]
)
df["Revenue_Check"] = (
    df["Revenue"] == df["Calculated_Revenue"]
)
df["Revenue_Check"].value_counts()

Revenue_Check
True    1200
Name: count, dtype: int64

Feature engineering

In [22]:
df["Year"] = df["Order_Date"].dt.year
df["Month"] = df["Order_Date"].dt.month
df["Month_Name"] = df["Order_Date"].dt.strftime("%B")
df["Quarter"] = df["Order_Date"].dt.quarter

Save cleaned data

02_python/output

In [27]:
import os

os.makedirs("output", exist_ok=True)

cleaned_df = df.drop(
    columns=["Calculated_Revenue", "Revenue_Check"]
)

cleaned_df.to_csv(
    "output/Lulu_Mall_Sales_Cleaned.csv",
    index=False
)