# Product Recommendation System

## Objective

The objective of this analysis is to develop a product recommendation
system using customer purchase behavior.

The system identifies products that are commonly purchased by customers
with similar purchasing patterns and recommends relevant products.

## Approach

1. Load the cleaned Lulu Mall sales dataset.
2. Create a customer-product interaction matrix.
3. Calculate similarity between products based on customer purchases.
4. Generate product recommendations.
5. Display recommended products for selected products.

step 1: Load Data

In [1]:
import pandas as pd
import numpy as np
df = pd.read_excel( r"D:\Lulu_Mall_Retail_Analytics recent\Lulu_Mall_Sales_Dataset.xlsx")
df.head()

,Order_ID,Order_Date,Store_ID,Store_Name,City,State,Region,Customer_ID,Customer_Gender,Product_Category,Product_Name,Quantity,Unit_Price,Revenue,Payment_Mode
0,ORD0100,2024-01-01,STR005,Lulu Mall Mumbai,Mumbai,Maharashtra,West,CUST0556,Female,Fashion,Adidas Women's Sports Shoes,1,5123,5123,UPI
1,ORD0763,2024-01-01,STR007,Lulu Mall Lucknow,Lucknow,Uttar Pradesh,North,CUST0073,Female,Beauty,Dove Body Lotion 400ml,1,571,571,UPI
2,ORD0654,2024-01-02,STR005,Lulu Mall Mumbai,Mumbai,Maharashtra,West,CUST0260,Male,Grocery,Haldiram's Bhujia Sev 1kg,3,439,1317,Net Banking
3,ORD0485,2024-01-03,STR003,Lulu Mall Chennai,Chennai,Tamil Nadu,South,CUST0727,Male,Electronics,Redmi Note 13 Pro,1,22889,22889,EMI
4,ORD0926,2024-01-03,STR003,Lulu Mall Chennai,Chennai,Tamil Nadu,South,CUST0242,Male,Fashion,Raymond Men's Formal Shirt,2,2373,4746,EMI

Step 2 Check the required columns

In [2]:
df[["Customer_ID", "Product_Name", "Quantity"]].head()

  Customer_ID                 Product_Name  Quantity
0    CUST0556  Adidas Women's Sports Shoes         1
1    CUST0073       Dove Body Lotion 400ml         1
2    CUST0260    Haldiram's Bhujia Sev 1kg         3
3    CUST0727            Redmi Note 13 Pro         1
4    CUST0242   Raymond Men's Formal Shirt         2

Step 3: Create Customer × Product matrix

In [3]:
customer_product_matrix = df.pivot_table(
    index="Customer_ID",
    columns="Product_Name",
    values="Quantity",
    aggfunc="sum",
    fill_value=0
)
customer_product_matrix.head()

Product_Name,Adidas Women's Sports Shoes,Amul Gold Full Cream Milk 6 Litres,Apple iPhone 15,Arrow Men's Formal Trouser,Bajaj 750W Mixer Grinder,Biotique Bio Sunscreen SPF60,Britannia Digestive Biscuits Multipack,Canon EOS 200D Camera,Crompton 25L Geyser Water Heater,Dell Inspiron Laptop,...,"Samsung 55"" Smart TV",Samsung Galaxy Tab S9,Sony Headphones WH-1000XM5,Tata Salt Iodized 1kg Pack of 5,Titan Raga Ladies Watch,Tropicana Orange Juice 1L Pack of 6,Usha Table Fan 3 Speed,VLCC Anti Aging Serum 30ml,Voltas 1.5T 3 Star Split AC,W Women's Casual Dress
Customer_ID,,,,,,,,,,,,,,,,,,,,,
CUST0001,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
CUST0002,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CUST0003,0,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CUST0005,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
CUST0006,0,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Step 4: Calculate product similarity

## Product Similarity

Cosine similarity is used to measure how similar two products are
based on customer purchasing behavior.

Products purchased by similar groups of customers will receive
higher similarity scores.

In [4]:
from sklearn.metrics.pairwise import cosine_similarity

product_similarity = cosine_similarity(customer_product_matrix.T)

product_similarity_df = pd.DataFrame(
    product_similarity,
    index=customer_product_matrix.columns,
    columns=customer_product_matrix.columns
)

product_similarity_df.head()

Product_Name,Adidas Women's Sports Shoes,Amul Gold Full Cream Milk 6 Litres,Apple iPhone 15,Arrow Men's Formal Trouser,Bajaj 750W Mixer Grinder,Biotique Bio Sunscreen SPF60,Britannia Digestive Biscuits Multipack,Canon EOS 200D Camera,Crompton 25L Geyser Water Heater,Dell Inspiron Laptop,...,"Samsung 55"" Smart TV",Samsung Galaxy Tab S9,Sony Headphones WH-1000XM5,Tata Salt Iodized 1kg Pack of 5,Titan Raga Ladies Watch,Tropicana Orange Juice 1L Pack of 6,Usha Table Fan 3 Speed,VLCC Anti Aging Serum 30ml,Voltas 1.5T 3 Star Split AC,W Women's Casual Dress
Product_Name,,,,,,,,,,,,,,,,,,,,,
Adidas Women's Sports Shoes,1.000000,0.046386,0.015529,0.000000,0.000000,0.000000,0.000000,0.000000,0.041812,0.064137,...,0.063836,0.011856,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.024593
Amul Gold Full Cream Milk 6 Litres,0.046386,1.000000,0.051503,0.064103,0.116712,0.034669,0.031388,0.006934,0.008667,0.031908,...,0.047049,0.014746,0.047919,0.035977,0.105433,0.016394,0.000000,0.047565,0.087706,0.040782
Apple iPhone 15,0.015529,0.051503,1.000000,0.008584,0.101126,0.000000,0.000000,0.000000,0.000000,0.056969,...,0.007875,0.000000,0.048125,0.048176,0.014118,0.000000,0.000000,0.000000,0.000000,0.013653
Arrow Men's Formal Trouser,0.000000,0.064103,0.008584,1.000000,0.054924,0.000000,0.167401,0.000000,0.011556,0.021272,...,0.000000,0.000000,0.031946,0.020559,0.000000,0.036430,0.000000,0.000000,0.043853,0.000000
Bajaj 750W Mixer Grinder,0.000000,0.116712,0.101126,0.054924,1.000000,0.000000,0.000000,0.009901,0.000000,0.000000,...,0.033593,0.014038,0.000000,0.000000,0.015056,0.156069,0.009274,0.000000,0.000000,0.000000

## Recommendation function
STEP 5

In [5]:
def recommend_products(product_name, n=5):
    
    if product_name not in product_similarity_df.index:
        return f"Product '{product_name}' not found in dataset."
    
    similar_products = product_similarity_df[product_name].sort_values(
        ascending=False
    )
    
    recommendations = similar_products.iloc[1:n+1]
    
    return recommendations

STEP 6 : Test it

In [7]:
df["Product_Name"].unique()

<ArrowStringArray>
[           'Adidas Women's Sports Shoes',
                 'Dove Body Lotion 400ml',
              'Haldiram's Bhujia Sev 1kg',
                      'Redmi Note 13 Pro',
             'Raymond Men's Formal Shirt',
            'Nescafe Classic Coffee 200g',
                   'Dell Inspiron Laptop',
              'Fresh Fruits Combo Basket',
         'Eureka Forbes Roboclean Vacuum',
                 'Nike Running Shoes Men',
             'Arrow Men's Formal Trouser',
       'Crompton 25L Geyser Water Heater',
        'Tata Salt Iodized 1kg Pack of 5',
           'Biotique Bio Sunscreen SPF60',
      'Kent Grand Plus RO Water Purifier',
                 'W Women's Casual Dress',
            'Voltas 1.5T 3 Star Split AC',
                  'Samsung Galaxy Tab S9',
       'Fortune Refined Sunflower Oil 5L',
                      'Philips Air Fryer',
          'LG Front Load Washing Machine',
               'Bajaj 750W Mixer Grinder',
             'Fabindia Women's Kurta Set',
     'Forest Essentials Luxury Face Wash',
 'Organic India Premium Basmati Rice 5kg',
                 'Puma Men's Track Pants',
 'Britannia Digestive Biscuits Multipack',
                'Titan Raga Ladies Watch',
     'Amul Gold Full Cream Milk 6 Litres',
    'Tropicana Orange Juice 1L Pack of 6',
      'MTR Ready-to-Eat Meals Pack of 10',
                   'Samsung 55" Smart TV',
               'Philips Steam Iron 2400W',
                    'H&M Women's Handbag',
      'Himalaya Purifying Neem Face Wash',
                'Nykaa Lipstick Set of 5',
                        'Apple iPhone 15',
         'Mamaearth Onion Hair Oil 250ml',
                 'Usha Table Fan 3 Speed',
            'Havells Ceiling Fan Premium',
         'JBL Portable Bluetooth Speaker',
     'Prestige Electric Rice Cooker 1.8L',
            'Levi's Men's Slim Fit Jeans',
    'L'Oreal Paris Revitalift Face Cream',
    'Park Avenue Signature Perfume 100ml',
        'Lakme Absolute Foundation SPF15',
             'Sony Headphones WH-1000XM5',
             'VLCC Anti Aging Serum 30ml',
                  'Canon EOS 200D Camera',
                'Morphy Richards OTG 60L']
Length: 50, dtype: str

In [9]:
recommendations = recommend_products("Samsung Galaxy Tab S9", 5)
recommendations

Product_Name
Park Avenue Signature Perfume 100ml    0.079205
Usha Table Fan 3 Speed                 0.073032
LG Front Load Washing Machine          0.071386
Mamaearth Onion Hair Oil 250ml         0.071245
Dell Inspiron Laptop                   0.059806
Name: Samsung Galaxy Tab S9, dtype: float64

# Personalized Recommendation System

The recommendation system supports two recommendation approaches:

1. Product-based recommendations
2. Customer-based personalized recommendations

Product-based recommendations identify products with similar
customer purchasing patterns.

Customer-based recommendations identify products that a customer
has not purchased yet but are frequently purchased by customers
with similar purchasing behavior.

customer-based recommendations

In [10]:
def recommend_for_customer(customer_id, n=5):

    if customer_id not in customer_product_matrix.index:
        return pd.DataFrame(
            columns=["Product_Name", "Score"]
        )

    customer_vector = customer_product_matrix.loc[
        customer_id
    ].values.reshape(1, -1)

    customer_similarity = cosine_similarity(
        customer_vector,
        customer_product_matrix.values
    )[0]

    similarity_scores = pd.Series(
        customer_similarity,
        index=customer_product_matrix.index
    )

    similarity_scores = similarity_scores.drop(
        customer_id,
        errors="ignore"
    )

    similar_customers = similarity_scores.sort_values(
        ascending=False
    )

    purchased_products = set(
        customer_product_matrix.loc[customer_id]
        .loc[lambda x: x > 0]
        .index
    )

    scores = {}

    for similar_customer, similarity in similar_customers.head(20).items():

        products = customer_product_matrix.loc[
            similar_customer
        ]

        for product, quantity in products.items():

            if quantity > 0 and product not in purchased_products:

                scores[product] = (
                    scores.get(product, 0)
                    + similarity * quantity
                )

    recommendations = (
        pd.Series(scores)
        .sort_values(ascending=False)
        .head(n)
        .reset_index()
    )

    recommendations.columns = [
        "Product_Name",
        "Score"
    ]

    return recommendations

In [11]:
customer_product_matrix.index[:10]

Index(['CUST0001', 'CUST0002', 'CUST0003', 'CUST0005', 'CUST0006', 'CUST0007',
       'CUST0009', 'CUST0010', 'CUST0011', 'CUST0013'],
      dtype='str', name='Customer_ID')

In [13]:
customer_id = customer_product_matrix.index[0]

recommend_for_customer('CUST0002', 5)

                             Product_Name     Score
0       MTR Ready-to-Eat Meals Pack of 10  4.469267
1                 Titan Raga Ladies Watch  3.216497
2         Lakme Absolute Foundation SPF15  2.948839
3              Arrow Men's Formal Trouser  2.500000
4  Organic India Premium Basmati Rice 5kg  2.190890